project_id = "fupqwyzwjvlnklbazqjm"

[functions.send-custom-email]
verify_jwt = false

[functions.send-sms-verification]
verify_jwt = false

[functions.send-whatsapp-verification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-game-confirmation]
verify_jwt = false

[functions.send-game-summary]
verify_jwt = false