// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fupqwyzwjvlnklbazqjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1cHF3eXp3anZsbmtsYmF6cWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTgwNjMsImV4cCI6MjA3MjA3NDA2M30.I7ZG4OfYyeA4c4s7Irfylzr7qUpmcV-3S07nofHHGf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});